version: '2'
services:
    server:
        container_name: speedy_server
        build: ./server
        ports:
            - "80:80"
        depends_on:
            - db
        links:
            - db:reto3db
